#
# ==== General info ====
#
# * You can add your own handlers in this file but don't forget to
# add they into 'handlers' list.
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#
# * It's highly recommended to check that your handler
# can modify an entity in the such way. For example, you can't
# set a drop chance for items in hands of a human.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# handlers:     ### List of handlers' paths.
#               ### (* see description of <handler> below)
# - <handler1>
#   ...
# - <handlerN>
#
# All handlers will handle a CreatureSpawnEvent in sequence in which
# they are described in this option.
#

handlers:
  - fat-rabbit
  - rapid-creeper
  - iron-creep

#
# ==== Handler ====
#
# <handler>:
#   filter: <filter>   ### Filter that will be applied before modifications.
#                      ### By default, no filters will be applied.
#                      ### (* see description of <filter> below)
#
#   max-health: <float-value:0..?> ### A multiplier for max. health of an entity.
#                                  ### By default, max. health won't be modified.
#                                  ### (* see description of <float-value> below)
#
#   effects:  ### List of effects which will be applied to an entity.
#             ### By default, no effects will be applied.
#             ###
#             ### Path of each effect can be absolute from the root of the config
#             ### or relative to the current handler definition.
#
#     - <effect-path-rel>  ### Relative path.
#     - <effect-path-abs>  ### Absolute path.
#       ...
#     - <effect-pathN>
#
#   effect-path-rel: <effect> ### Effect described in handler's namespace.
#                             ### (* see description of <effect> below)
#
#   equipment: <equipment>    ### Modifications of entity's equipment.
#                             ### (* see description of <equipment> below)
#
# effect-path-abs: <effect>   ### Effect described anywhere else.
#
# #### Filter ####
#
# <filter>:  ### This section has descriptions of several filtering rules.
#            ### The filter will be passed only if all rules are passed.
#            ### But you should define at least one rule and avoid
#            ### passing all possible entities.
#
#   reasons: ### Possible spawn reasons, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#            ### By default, spawns with all reason will be processed.
#            ###
#            ### Hint: a spawn via "summon" command will be detected as "DEFAULT".
#     - <spawn-reason1>
#       ...
#     - <spawn-reasonN>
#
#   types:   ### Possible entity types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
#            ### By default, entities of all types will be processed.
#            ###
#            ### An entity should be a subinterface of LivingEntity, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html
#     - <entity-type1>
#       ...
#     - <entity-typeN>
#
#   probability: <0..100> ### Probability in percents that this handler will
#                         ### be applied after all the filters.
#                         ### By default the probability is 100%.
#
# #### Effect ####
#
# <effect>:
#   types:   ### Effect types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#            ### Effects of all these types will be applied to an entity.
#     - <effect-type1>
#       ...
#     - <effect-typeN>
#
#   strength: <int-value:0..?>   ### Strength of the effect.
#                                ### (* see description of <int-value> below)
#   duration: <int-value:0..?>   ### Duration of the effect, in seconds.
#
# #### Equipment ####
#
# <equipment>:
#   helmet: <equipment-cloth>   ### Description of entity's helmet.
#                               ### (* see description of <equipment-cloth> below)
#   boots: <equipment-cloth>    ### Description of entity's boots.
#   chest: <equipment-cloth>    ### Description of entity's chest.
#   pens: <equipment-cloth>     ### Description of entity's pens.
#   main-hand: <item-in-hand>   ### Description of entity's main hand equipment
#                               ### (* see description of <item-in-hand> below)
#   off-hand: <item-in-hand>    ### Description of entity's off hand equipment
#                               ###
#                               ### Warning: off hand configuration works only with
#                               ### Minecraft version greater or equal 1.9.0
#
# #### Equipment cloth ####
#
# <equipment-cloth>:
#   probability: <0..100>   ### Probability in percents that this cloth will
#                           ### be dressed on the entity.
#                           ### By default the probability is 100%.
#
#   material-type: <material-type> ### Material of the cloth. Possible values:
#                                  ###  - LEATHER
#                                  ###  - CHAINMAIL
#                                  ###  - IRON
#                                  ###  - DIAMOND
#                                  ###  - GOLD
#
#   drop-chance: <0..100> ### Chance that this cloth will be dropped as
#                         ### an award for the killer.
#                         ### By default the probability is 0%.
#
#   durability: <int-value:0..100>  ### Durability in percents of this cloth.
#                                   ### By default the durability is 100%.
#
#   enchantments <enchantments>:  ### List of enchantments will be applied to this cloth.
#                                 ### By default, no enchantments will be applied.
#                                 ### (* see description of <enchantments> below)
#
# #### Item in hand ####
#
# <item-in-hand>:
#   probability: <0..100>   ### Probability in percents that this item will
#                           ### be in hand of the entity.
#                           ### By default the probability is 100%.
#
#   material: <material>    ### Material of the item, see:
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
#   amount: <int-value:1..64> ### Amount of items.
#
#   drop-chance: <0..100> ### Chance that this item will be dropped as
#                         ### an award for the killer.
#                         ### By default the probability is 0%.
#
#   durability: <int-value:0..100>  ### Durability in percents of this item.
#                                   ### By default the durability is 100%.
#
#   enchantments <enchantments>:  ### List of enchantments will be applied to this item.
#                                 ### By default, no enchantments will be applied.
#                                 ### (* see description of <enchantments> below)
#
# #### Enchantments ####
#
# <relative-path>:
#   <enchantments>:  ### List of enchantments' paths.
#                    ### Path of each enchantment can be absolute from the root of the config
#                    ### or relative to the current <relative-path> definition.
#
#     - <enchantment-path-rel>  ### Relative path.
#     - <enchantment-path-abs>  ### Absolute path.
#       ...
#     - <enchantment-pathN>
#
#   enchantment-path-rel: <enchantment> ### Enchantment described in <relative-path> namespace.
#                                       ### (* see description of <enchantment> below)
#
# enchantment-path-abs: <enchantment>   ### Enchantment described anywhere else.
#
# #### Enchantment ####
#
# <enchantment>:
#   type: <enchantment-type>  ### Enchantment type, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#                             ###
#                             ### Hint: common protection's enchantment
#                             ### is "PROTECTION_ENVIRONMENTAL".
#
#   level: <int-value:1..5>   ### Level of enchantment.
#
# #### Floating point value ####
#
# <float-value>: <float>      ### Normal floating point value.
# ||
# <float-value>:
#   type: random              ### Type of floating point value. Currently
#                             ### only 'random' type is supported.
#   min: <float>              ### Minumum value.
#   max: <float>              ### Maximum value.
#   distribution: <rnd-distr> ### Type of random distribution.
#                             ### (* see description of <rnd-distr> below)
#
# #### Integer value ####
#
# <int-value>: <int>          ### Normal integer value.
# ||
# <int-value>:
#   type: random              ### Random integer value. Currently
#                             ### only 'random' type is supported.
#   min: <int>                ### Minumum value.
#   max: <int>                ### Maximum value.
#   distribution: <rnd-distr> ### Type of random distribution.
#                             ### (* see description of <rnd-distr> below)
#
# #### Random distribution ####
#
# <rnd-distr>: normal | exp_up | exp_down
# ### normal - normal distribution with uniform density from min to max, e.g. 33%, 33%, 33%.
# ### exp_up - exponential distribution with growing density from min to max, e.g. 10%, 25%, 65%.
# ### exp_down - exponential distribution with falling density from min to max, e.g. 65%, 25%, 10%.
# ###
# ### By default, a NORMAL distribution will be chosen.
#

fat-rabbit:
  filter:
    reasons:
      - NATURAL
    types:
      - RABBIT
    probability: 5
  max-health:
    type: random
    min: 2.0
    max: 4.0
    distribution: exp_down

rapid-creeper:
  filter:
    types:
      - CREEPER
    probability: 5
  effects:
    - acceleration
  acceleration:
    types:
      - SPEED
    strength:
      type: random
      min: 1
      max: 10
      distribution: exp_down
    duration: 99999

iron-creep:
  filter:
    reasons:
      - DEFAULT
    types:
      - ZOMBIE
      - SKELETON
      - PLAYER
      - CREEPER
    probability: 100
  equipment:
    helmet:
      drop-chance: 100
      material-type: IRON
      durability: 50
      enchantments:
        - enchantments.high_protection
    boots:
      drop-chance: 100
      material-type: IRON
      durability: 50
      enchantments:
        - enchantments.high_protection
    chest:
      drop-chance: 100
      material-type: IRON
      durability: 50
      enchantments:
        - enchantments.high_protection
    leggings:
      drop-chance: 100
      material-type: IRON
      durability: 50
      enchantments:
        - enchantments.high_protection
    main-hand:
      drop-chance: 100
      material: IRON_SWORD
      amount: 1
    off-hand:
      drop-chance: 100
      material: GOLD_SWORD
      amount: 20
    saddle:
    armor:
  max-health: 0.01

enchantments:
  high_protection:
    type: PROTECTION_ENVIRONMENTAL
    level: 4