#
# ==== General info ====
# 
# * You can add your own handlers in this file but don't forget to
# add they into 'handlers' list
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance
#
debug: false

#
# handlers:     ### List of handlers' paths
#               ### (* see description of <handler> below)
# - <handler1>
#   ...
# - <handlerN>
#
# All handlers will handle a CreatureSpawnEvent in sequence in which
# they are described in this option
#

handlers:
  - fat-rabbit
  - rapid-creeper
  - iron-creep
    
#
# ==== Handler ====
#
# <handler>:
#   filter: <filter>   ### Filter that will be applied before modifications.
#                      ### By default, no filters will be applied.
#                      ### (* see description of <filter> below)
#
#   max-health: <float-value> ### A multiplier for max. health of an entity.
#                             ### (* see description of <float-value> below)
#
#   effects:  ### List of effects which will be applied to an entity.
#             ### Path of each effect can be absolute from the root of the config
#             ### or relative to the current handler definition.
#
#     - <effect-path-rel>  ### Relative path
#     - <effect-path-abs>  ### Absolute path
#       ...
#     - <effect-pathN>
#
#   effect-path-rel: <effect> ### Effect described in handler's namespace
#                             ### (* see description of <effect> below)
# effect-path-abs: <effect>   ### Effect described anywhere else
#
# #### Filter ####
#
# <filter>:
#   reasons: ### Possible spawn reasons, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#            ### By default, spawns with all reason will be processed.
#            ### Hint: a spawn via "summon" command will be detected
#            ### as "DEFAULT"
#     - <spawn-reason1>
#       ...
#     - <spawn-reasonN>
#
#   types:   ### Possible entity types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
#            ### By default, entities of all types will be processed.
#            ###
#            ### An entity should be a subinterface of LivingEntity, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html
#     - <entity-type1>
#       ...
#     - <entity-typeN>
#
#   probability: <0..100> ### Probability in percents that this handler will
#                         ### be applied after all the filters.
#                         ### (default = 100)
#
# #### Effect ####
#
# <effect>:
#   types:   ### Effect types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#            ### Effects of all these types will be applied to an entity
#     - <effect-type1>
#       ...
#     - <effect-typeN>
#
#   strength:  <int-value>   ### Strength of the effect
#                            ### (* see description of <int-value> below)
#   duration:  <int-value>   ### Duration of the effect, in seconds
#
# #### Floating point value ####
#
# <float-value>: <float>      ### Normal floating point value
# ||
# <float-value>:
#   type: random              ### Type of floating point value. Currently
#                             ### only 'random' type is supported.
#   min: <float>              ### Minumum value
#   max: <float>              ### Maximum value
#   distribution: <rnd-distr> ### Type of random distribution
#                             ### (* see description of <rnd-distr> below)
#
# #### Integer value ####
#
# <int-value>: <int>          ### Normal integer value
# ||
# <int-value>:
#   type: random              ### Random integer value. Currently
#                             ### only 'random' type is supported.
#   min: <int>                ### Minumum value
#   max: <int>                ### Maximum value
#   distribution: <rnd-distr> ### Type of random distribution
#                             ### (* see description of <rnd-distr> below)
#
# #### Random distribution ####
#
# <rnd-distr>: normal | exp_up | exp_down
# ### normal - normal distribution with uniform density from min to max, e.g. 33%, 33%, 33%
# ### exp_up - exponential distribution with growing density from min to max, e.g. 10%, 25%, 65%
# ### exp_down - exponential distribution with falling density from min to max, e.g. 65%, 25%, 10%
#

fat-rabbit:
  filter:
    reasons:
      - NATURAL
    types:
      - RABBIT
    probability: 5
  max-health:
    type: random
    min: 2.0
    max: 4.0
    distribution: exp_down

rapid-creeper:
  filter:
    types:
      - CREEPER
    probability: 5
  effects:
    - acceleration
  acceleration:
    types:
      - SPEED
    strength:
      type: random
      min: 1
      max: 10
      distribution: exp_down
    duration: 99999

iron-creep:
  filter:
    reasons:
      - DEFAULT
    types:
      - ZOMBIE
      - SKELETON
    probability: 100
  equipment:
    helmet:
      drop-chance: 100
      material: IRON
      enchantments:
        - strong_helm
      strong_helm:
        type: PROTECTION_ENVIRONMENTAL
        level: 4
    boots:
      drop-chance: 100
      material: IRON
      probability: 100
      enchantments:
        - strong_boots
      strong_boots:
        type: PROTECTION_ENVIRONMENTAL
        level: 4
    chest:
    pens:
    main-hand:
    saddle:
    armor:
    off-hand:
      item: IRON
      count: 8
      drop-chance: 100