#
# ==== General info ====
#
# * You can add your own handlers in this file but don't forget to
# add they into 'handlers' list.
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#
# * It's highly recommended to check that your handler
# can modify an entity in the such way. For example, you can't
# set a drop chance for items in hands of a human.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# handlers:     ### List of handlers' paths.
#               ### (* see description of <handler> below)
# - <handler1>
#   ...
# - <handlerN>
#
# All handlers will handle a CreatureSpawnEvent in sequence in which
# they are described in this option.
#

handlers:
  - fat-animal
  - rapid-monster
  - player
  - iron-zombie
  - gold-zombie
  - diamond-skeleton

#
# ==== Handler ====
#
# <handler>:
#   filter: <filter>   ### Filter that will be applied before modifications.
#                      ### By default, no filters will be applied.
#                      ### (* see description of <filter> below)
#
#   max-health: <float-value:0.0001..?> ### A multiplier for max. health of an entity.
#                                       ### By default, max. health won't be modified.
#                                       ### (* see description of <float-value> below)
#                                       ###
#                                       ### Warning: player's max health is saved on disk
#                                       ### and each new change will be applied cumulatively.
#
#   effects:  ### List of effects which will be applied to an entity.
#             ### By default, no effects will be applied.
#             ###
#             ### Path of each effect can be absolute from the root of the config
#             ### or relative to the current handler definition.
#
#     - <effect-path-rel>  ### Relative path.
#     - <effect-path-abs>  ### Absolute path.
#       ...
#     - <effect-pathN>
#
#   effect-path-rel: <effect> ### Effect described in handler's namespace.
#                             ### (* see description of <effect> below)
#
#   equipment: <equipment>    ### Modifications of entity's equipment.
#                             ### (* see description of <equipment> below)
#
# effect-path-abs: <effect>   ### Effect described anywhere else.
#
# #### Filter ####
#
# <filter>:  ### This section has descriptions of several filtering rules.
#            ### The filter will be passed only if all rules are passed.
#            ### But you should define at least one rule and avoid
#            ### passing all possible entities.
#
#   reasons: ### Possible spawn reasons, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#            ### By default, spawns with all reason will be processed.
#            ###
#            ### Hint: a spawn via "summon" command will be detected as "DEFAULT".
#     - <spawn-reason1>
#       ...
#     - <spawn-reasonN>
#
#   types:   ### Possible entity types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
#            ### By default, entities of all types will be processed.
#            ###
#            ### An entity should be a subinterface of LivingEntity, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html
#     - <entity-type1>
#       ...
#     - <entity-typeN>
#
#   type-sets:  ### Pre-defined sets of possible entity types.
#               ### By default, entities of all types will be processed.
#               ###
#               ### If you define both "types" and "type-sets" filters,
#               ### then entity types will be merged.
#               ### So, you can define types as [ZOMBIE] and type-sets as [ANIMALS].
#               ###
#     - <type-set1>   ### (* see description of <type-set> below)
#       ...
#     - <type-setN>
#
#   probability: <0..100> ### Probability in percents that this handler will
#                         ### be applied after all the filters.
#                         ### By default the probability is 100%.
#
# #### Type set ####
#
# A set of entity types. Some living entities do not belong to any groups:
# [SLIME, MAGMA_CUBE, SQUID, PLAYER]
#
# <type-set>: ANIMALS | GOLEMS | MONSTERS | CREATURES | FLYING
#
# ANIMALS: [CHICKEN, COW, HORSE, MUSHROOM_COW, OCELOT, PIG, POLAR_BEAR, RABBIT, SHEEP, WOLF]
# GOLEMS: [IRON_GOLEM, SHULKER, SNOWMAN]
# MONSTERS: [BLAZE, CAVE_SPIDER, CREEPER, ENDERMAN, ENDERMITE, GIANT, GUARDIAN, PIG_ZOMBIE,
#            SILVERFISH, SKELETON, SPIDER, WITCH, WITHER, ZOMBIE]
# CREATURES (includes [ANIMALS, GOLEMS, MONSTERS]): [BAT, VILLAGER]
# FLYING: [ENDER_DRAGON, GHAST]
#
# #### Effect ####
#
# <effect>:
#   types:   ### Effect types, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#            ### Effects of all these types will be applied to an entity.
#     - <effect-type1>
#       ...
#     - <effect-typeN>
#
#   strength: <int-value:1..?>   ### Strength of the effect.
#                                ### (* see description of <int-value> below)
#   duration: <int-value:1..?>   ### Duration of the effect, in seconds.
#
# #### Equipment ####
#
# <equipment>:
#   helmet: <equipment-cloth>   ### Description of entity's helmet.
#                               ### (* see description of <equipment-cloth> below)
#   boots: <equipment-cloth>    ### Description of entity's boots.
#   chest: <equipment-cloth>    ### Description of entity's chest.
#   pens: <equipment-cloth>     ### Description of entity's pens.
#   main-hand: <item-in-hand>   ### Description of entity's main hand equipment
#                               ### (* see description of <item-in-hand> below)
#   off-hand: <item-in-hand>    ### Description of entity's off hand equipment
#                               ###
#                               ### Warning: off hand configuration works only with
#                               ### Minecraft version greater or equal 1.9.0
#
# #### Equipment cloth ####
#
# <equipment-cloth>:
#   probability: <0..100>   ### Probability in percents that this cloth will
#                           ### be dressed on the entity.
#                           ### By default the probability is 100%.
#
#   material-type: <material-type> ### Material of the cloth. Possible values:
#                                  ###  - LEATHER
#                                  ###  - CHAINMAIL
#                                  ###  - IRON
#                                  ###  - DIAMOND
#                                  ###  - GOLD
#
#   drop-chance: <0..100> ### Chance that this cloth will be dropped as
#                         ### an award for the killer.
#                         ### By default the probability is 0%.
#
#   durability: <int-value:0..100>  ### Durability in percents of this cloth.
#                                   ### By default the durability is 100%.
#
#   enchantments <enchantments>:  ### List of enchantments will be applied to this cloth.
#                                 ### By default, no enchantments will be applied.
#                                 ### (* see description of <enchantments> below)
#
# #### Item in hand ####
#
# <item-in-hand>:
#   probability: <0..100>   ### Probability in percents that this item will
#                           ### be in hand of the entity.
#                           ### By default the probability is 100%.
#
#   material: <material>    ### Material of the item, see:
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
#   amount: <int-value:1..64> ### Amount of items.
#
#   drop-chance: <0..100> ### Chance that this item will be dropped as
#                         ### an award for the killer.
#                         ### By default the probability is 0%.
#
#   durability: <int-value:0..100>  ### Durability in percents of this item.
#                                   ### By default the durability is 100%.
#
#   enchantments <enchantments>:  ### List of enchantments will be applied to this item.
#                                 ### By default, no enchantments will be applied.
#                                 ### (* see description of <enchantments> below)
#
# #### Enchantments ####
#
# <relative-path>:
#   <enchantments>:  ### List of enchantments' paths.
#                    ### Path of each enchantment can be absolute from the root of the config
#                    ### or relative to the current <relative-path> definition.
#
#     - <enchantment-path-rel>  ### Relative path.
#     - <enchantment-path-abs>  ### Absolute path.
#       ...
#     - <enchantment-pathN>
#
#   enchantment-path-rel: <enchantment> ### Enchantment described in <relative-path> namespace.
#                                       ### (* see description of <enchantment> below)
#
# enchantment-path-abs: <enchantment>   ### Enchantment described anywhere else.
#
# #### Enchantment ####
#
# <enchantment>:
#   type: <enchantment-type>  ### Enchantment type, see
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#                             ###
#                             ### Hint: common protection's enchantment
#                             ### is "PROTECTION_ENVIRONMENTAL".
#
#   level: <int-value:1..5>   ### Level of enchantment.
#
# #### Floating point value ####
# High-level restrictions:
# - Maximum number of digits after the point is 4.
# - Maximum number of digits before the point is 11.
# - The minimal float point value is 0.0001.
# - The maximal float point value is 99999999999.9999.
#
# <float-value>: <float>      ### Normal floating point value.
# ||
# <float-value>:
#   type: random              ### Type of floating point value. Currently
#                             ### only 'random' type is supported.
#   min: <float>              ### Minumum value.
#   max: <float>              ### Maximum value.
#   distribution: <rnd-distr> ### Type of random distribution.
#                             ### (* see description of <rnd-distr> below)
#
# #### Integer value ####
#
# <int-value>: <int>          ### Normal integer value.
# ||
# <int-value>:
#   type: random              ### Random integer value. Currently
#                             ### only 'random' type is supported.
#   min: <int>                ### Minumum value.
#   max: <int>                ### Maximum value.
#   distribution: <rnd-distr> ### Type of random distribution.
#                             ### (* see description of <rnd-distr> below)
#
# #### Random distribution ####
#
# <rnd-distr>: normal | exp_up | exp_down
# ### normal - normal distribution with uniform density from min to max, e.g. 33%, 33%, 33%.
# ### exp_up - exponential distribution with growing density from min to max, e.g. 10%, 25%, 65%.
# ### exp_down - exponential distribution with falling density from min to max, e.g. 65%, 25%, 10%.
# ###
# ### By default, a NORMAL distribution will be chosen.
#

fat-animal:
  filter:
    reasons:
      - NATURAL
    type-sets:
      - ANIMALS
    probability: 5
  max-health:
    type: random
    min: 1.0
    max: 4.0
    distribution: exp_down

rapid-monster:
  filter:
    type-sets:
      - MONSTERS
    probability: 5
  effects:
    - acceleration
  acceleration:
    types:
      - SPEED
    strength:
      type: random
      min: 1
      max: 5
      distribution: exp_down
    duration: 99999

player:
  filter:
    reasons:
      - DEFAULT
    types:
      - PLAYER
  equipment:
    main-hand:
      material: APPLE

iron-zombie:
  filter:
    types:
      - ZOMBIE
    probability: 5
  effects:
    - acceleration
  acceleration:
    types:
      - SPEED
      - JUMP
    strength: 1
    duration: 99999

  equipment:
    helmet:
      drop-chance: 10
      material-type: IRON
      durability: 25
      enchantments:
        - enchantments.rand_protection
    boots:
      drop-chance: 10
      material-type: IRON
      durability: 25
      enchantments:
        - enchantments.rand_protection
    chest:
      drop-chance: 10
      material-type: IRON
      durability: 25
      enchantments:
        - enchantments.rand_protection
    leggings:
      drop-chance: 10
      material-type: IRON
      durability: 25
      enchantments:
        - enchantments.rand_protection
    main-hand:
      drop-chance: 10
      material: IRON_SWORD
      durability: 25
      enchantments:
        - enchantments.rand_sword_damage
  max-health: 2.0

gold-zombie:
  filter:
    types:
      - ZOMBIE
    probability: 2
  effects:
    - acceleration
    - damage
    - effects.fire_resistance
    - effects.regeneration
  acceleration:
    types:
      - SPEED
      - JUMP
    strength: 2
    duration: 99999
  damage:
    types:
      - INCREASE_DAMAGE
    strength: 4
    duration: 99999
  equipment:
    helmet:
      drop-chance: 10
      material-type: GOLD
      durability: 50
      enchantments:
        - enchantments.high_protection
    boots:
      drop-chance: 10
      material-type: GOLD
      durability: 50
      enchantments:
        - enchantments.high_durability
        - enchantments.high_protection
        - enchantments.rand_thorns
    chest:
      drop-chance: 10
      material-type: GOLD
      durability: 50
      enchantments:
        - enchantments.high_protection_fire
    leggings:
      drop-chance: 10
      material-type: GOLD
      durability: 50
      enchantments:
        - enchantments.high_protection
    main-hand:
      drop-chance: 5
      material: GOLD_SWORD
      durability: 50
      enchantments:
        - enchantments.high_durability
        - enchantments.high_sword_damage
        - enchantments.high_sword_knockback
        - enchantments.high_sword_fire_aspect
        - enchantments.high_sword_looting
  max-health: 3.0

diamond-skeleton:
  filter:
    types:
      - SKELETON
    probability: 1
  effects:
    - acceleration
    - glowing
    - effects.fire_resistance
    - effects.regeneration
  acceleration:
    types:
      - SPEED
      - JUMP
    strength: 3
    duration: 99999
  glowing:
    types:
      - GLOWING
    strength: 1
    duration: 60
  equipment:
    helmet:
      drop-chance: 5
      material-type: DIAMOND
      durability: 33
      enchantments:
        - enchantments.high_durability
        - enchantments.high_protection
        - enchantments.high_oxygen_helmet
        - enchantments.water_worker_helmet
        - enchantments.high_thorns
    boots:
      drop-chance: 5
      material-type: DIAMOND
      durability: 33
      enchantments:
        - enchantments.high_durability
        - enchantments.high_protection
        - enchantments.high_protection_fall_boots
        - enchantments.high_depth_strider_boots
        - enchantments.high_thorns
    chest:
      drop-chance: 5
      material-type: DIAMOND
      durability: 33
      enchantments:
        - enchantments.high_durability
        - enchantments.high_protection_fire
        - enchantments.high_thorns
    leggings:
      drop-chance: 5
      material-type: DIAMOND
      durability: 33
      enchantments:
        - enchantments.high_durability
        - enchantments.high_protection
        - enchantments.high_thorns
    main-hand:
      drop-chance: 5
      material: BOW
      durability: 33
      enchantments:
        - enchantments.high_durability
        - enchantments.high_bow_damage
        - enchantments.high_bow_knockback
        - enchantments.bow_fire
        - enchantments.bow_infinity
  max-health: 4.0

# Global templates of effects
effects:
  fire_resistance:
    types:
      - FIRE_RESISTANCE
    strength: 1
    duration: 99999
  regeneration:
    types:
      - REGENERATION
    strength: 1
    duration: 99999

# Global templates of enchantments
enchantments:
  # Mix
  rand_protection:
    type: PROTECTION_ENVIRONMENTAL
    level:
      type: random
      min: 1
      max: 4
      distribution: exp_down
  rand_sword_damage:
    type: DAMAGE_ALL
    level:
      type: random
      min: 1
      max: 5
      distribution: exp_down
  rand_thorns:
    type: THORNS
    level:
      type: random
      min: 1
      max: 3
      distribution: exp_down

  # Cloths and weapon
  high_durability:
    type: DURABILITY
    level: 3

  # Cloths
  high_protection:
    type: PROTECTION_ENVIRONMENTAL
    level: 4
  high_protection_fire:
    type: PROTECTION_FIRE
    level: 4
  high_protection_fall_boots:
    type: PROTECTION_FALL
    level: 4
  high_oxygen_helmet:
    type: OXYGEN
    level: 3
  water_worker_helmet:
    type: WATER_WORKER
    level: 1
  high_thorns:
    type: THORNS
    level: 3
  high_depth_strider_boots:
    type: DEPTH_STRIDER
    level: 3

  # Sword
  high_sword_damage:
    type: DAMAGE_ALL
    level: 5
  high_sword_knockback:
    type: KNOCKBACK
    level: 2
  high_sword_fire_aspect:
    type: FIRE_ASPECT
    level: 2
  high_sword_looting:
    type: LOOT_BONUS_MOBS
    level: 3

  # Bow
  high_bow_damage:
    type: ARROW_DAMAGE
    level: 5
  high_bow_knockback:
    type: ARROW_KNOCKBACK
    level: 2
  bow_fire:
    type: ARROW_FIRE
    level: 1
  bow_infinity:
    type: ARROW_INFINITE
    level: 1