name: CustomCreatures
main: com.gmail.uprial.customcreatures.CustomCreatures
version: 0.8.2
api-version: '1.20'
commands:
   customcreatures:
      description: Reload CustomCreatures config
      usage: /customcreatures help
      permission:
      permission-message:
permissions:
    customcreatures.reload:
        description: Gives access to CustomCreatures 'reload' command
        default: op