name: CustomCreatures
main: com.gmail.uprial.customcreatures.CustomCreatures
version: 0.15.1
api-version: '1.21'
commands:
   customcreatures:
      description: Reload CustomCreatures config
      usage: /customcreatures help
      permission:
      permission-message:
permissions:
    customcreatures.reload:
        description: Gives access to CustomCreatures 'reload' command
        default: op
    customcreatures.apply:
      description: Gives access to CustomCreatures 'apply' command
      default: op